Spw ranges fourier filter
HERA-Team/hera_cal pull request #725
Opened 2021-05-13 23:03 UTC by aewallwi

2021-07-22 23:11 UTC, jsdillon requested changes
Some minor changes, but otherwise looks fine.

One general comment I have is that this seems rather complicated for what it's trying to do, which I think will make it hard to maintain. It's not clear to me if it can be simplified without a significant loss of functionality, so I leave it to you @aewallwi to determine if it's sufficiently necessary to warrant the extra complexity.

2021-07-26 22:56 UTC, aewallwi commented on hera_cal/vis_clean.py
> +    """Find edges based on discontinuity in x-axis
I've added comments to explain this but basically, this function helps us find discontinuities in the x-axis which exist if we have several non-contiguous subbands in our data (for example, excising the FM band).

2021-07-26 23:10 UTC, aewallwi commented on hera_cal/vis_clean.py
> +        fractional discontinuity in diff of xs above which an edge will be identified.
I've clarified this.

Median would work as long as >50% of the channels are in fact contiguous.

2021-07-30 20:15 UTC, aewallwi commented on hera_cal/vis_clean.py
> +    edges : list of 2-tuples or 2-list of lists of 2-tuples
I've added an example that hopefully helps.

2021-07-30 21:05 UTC, aewallwi commented on hera_cal/vis_clean.py
> +        if len(inds_left) > 1:
i think your right. I've gotten rid of the conditional.

2021-07-30 21:18 UTC, aewallwi commented on hera_cal/vis_clean.py
> +        if isinstance(x, (tuple, list)) and len(x) == 2:
I don't see how? I think if x is a list of length 2 this conditional will eval as True?

2021-07-30 21:19 UTC, aewallwi commented on hera_cal/vis_clean.py
> +        if isinstance(x, (tuple, list)) and len(x) == 2:
OK, I think I see what you mean... x is a list of doubles.

2021-07-30 21:20 UTC, aewallwi commented on hera_cal/vis_clean.py
> +        if isinstance(x, (tuple, list)) and len(x) == 2:
I've modified this line to make sure the elements of x are ndarrays, lists, or tuples as well.

2021-07-30 21:20 UTC, aewallwi commented on hera_cal/vis_clean.py
>      if len(x) == 2:
See response above.

2021-07-30 21:27 UTC, aewallwi commented on hera_cal/vis_clean.py
> +        dx = [np.median(np.diff(x[0])), np.median(np.diff(x[1]))]
I've added an exception to catch this

2021-07-30 21:34 UTC, aewallwi commented on hera_cal/vis_clean.py
> +        if len(self.freqs) != np.sum([spw_range[1] - spw_range[0] for spw_range in filter_spw_ranges]) or not np.allclose(self.freqs, self.freqs[np.hstack([np.arange(spw_range[0], spw_range[1]).astyp
I've broken this one up.

2021-07-30 21:40 UTC, aewallwi commented on hera_cal/vis_clean.py
> +            raise NotImplementedError("No support for spw-ranges that do not disjointly cover the entire frequency band.")
This is checking whether all of the channels in the original frequency axis are contained in one of the user specified SPWs. I've made the error state this more clearly.

2021-07-30 21:41 UTC, aewallwi commented on hera_cal/vis_clean.py
> +                        print(chunks[0], edges[0])
Thanks for catching this. These should have been deleted.

2021-07-30 22:50 UTC, aewallwi commented
Thanks for the review @jsdillon! This is ready for another look whenever you get a chance.

2021-08-02 18:45 UTC, jsdillon approved these changes
Looks good to me!

2021-08-02 19:46 UTC, merged