Fast io cal
HERA-Team/hera_cal pull request #803
Opened 2022-06-06 18:51 UTC by AaronParsons

Adds io.read_hera_calfits for quick reading of calfits files.

2022-06-07 15:40 UTC, jsdillon requested changes
Nice stuff! I've got a handful of relatively minor change requests.

Two other things: 
1) It'd be nice to show some example (screenshots) of the speedups involved here.
2) `read_hera_calfits()` is a bit light on inline comments

2022-06-07 21:28 UTC, AaronParsons commented on hera_cal/io.py
> +                gain_convention = hdr.pop("GNCONVEN")
Done

2022-06-07 21:29 UTC, AaronParsons commented on hera_cal/io.py
> +                x_orient = hdr['XORIENT']
Done

2022-06-07 21:31 UTC, AaronParsons commented on hera_cal/io.py
> +def read_hera_calfits(filenames, ants=None, pols=None,
Done

2022-06-07 21:41 UTC, AaronParsons commented on hera_cal/tests/test_io.py
> +class Test_ReadHeraCalfits(object):
urk

2022-06-08 19:07 UTC, AaronParsons commented on hera_cal/tests/test_io.py
> +
Done.

2022-06-08 19:08 UTC, AaronParsons commented on hera_cal/io.py
> +    but does not check that files are contiguous.
Done.

2022-06-09 00:55 UTC, jsdillon approved these changes

2022-06-09 00:55 UTC, merged