Firstcal offsets
HERA-Team/hera_cal pull request #839
Opened 2022-10-11 19:54 UTC by AaronParsons

OoM speedup to firstcal

2022-10-11 20:25 UTC, jsdillon commented on hera_cal/redcal.py
>              conv_crit: convergence criterion for iterative offset solver, defined as the L2 norm
You can dump `conv_crit` from the docstring.

2022-10-11 20:30 UTC, jsdillon commented on hera_cal/tests/test_redcal.py
> +        meta, g_fc = rc.firstcal(d, freqs)
I'd suggest changing `g_fc` to `sol_fc` or similar to clarify what it actually is.

2022-10-11 20:30 UTC, jsdillon commented on hera_cal/tests/test_redcal.py
> +        meta, g_fc = rc.firstcal(d, freqs)
Same comment here.

2022-10-11 20:31 UTC, jsdillon commented on hera_cal/tests/test_redcal.py
>              om._build_polarity_baseline_groups(data, reds, max_rel_angle=np.pi)
```
with pytest.raises(ValueError):
            om._build_polarity_baseline_groups(data, reds, max_rel_angle=np.pi)
```
is outdated and can be removed

2022-10-11 20:33 UTC, jsdillon commented on hera_cal/utils.py
> +def quinn_tau(x):
This should probably have at least a one-line docstring.

2022-10-11 20:44 UTC, jsdillon commented on hera_cal/redcal.py
> +        changed = 0
I personally find it a lot more readable to make these bools instead of ints.

2022-10-11 20:46 UTC, jsdillon commented on hera_cal/tests/test_redcal.py
>              om._build_polarity_baseline_groups(data, reds, max_rel_angle=np.pi)
I just did it so tests would pass

2022-10-11 21:09 UTC, jsdillon commented on hera_cal/redcal.py
> +            np.divide(data, gij, out=data, where=(gij != 0))
This branch is not covered by tests.

2022-10-11 21:34 UTC, jsdillon commented on hera_cal/redcal.py
> +        rv['fc_meta'], rv['g_firstcal'] = rc.firstcal(data, freqs)
I think something like this would be clearer to read:
```
rv['fc_meta'], fc_sol = rc.firstcal(data, freqs)
rv['g_firstcal'] = fc_sol.gains
``

2022-10-11 21:35 UTC, jsdillon requested changes
This is really awesome work! Just a handful of cosmetic tweaks and clarifications and I think we'll be good to go.

2022-10-11 22:25 UTC, jsdillon commented on hera_cal/redcal.py
> +                'polarity_flips': {ant: np.ones(Ntimes) * int(ant in flipped) for ant in ants}}
Can you make these bools instead of ints to preserve the interface?

2022-10-11 22:47 UTC, jsdillon commented on hera_cal/redcal.py
>              g_fc: dictionary of Ntimes x Nfreqs per-antenna gains solutions in the
The return docstring on `g_fc` is now out of date.

2022-10-12 00:26 UTC, AaronParsons commented
@jsdillon Assuming this passes, I addressed all your comments.

2022-10-12 03:09 UTC, jsdillon approved these changes

2022-10-12 03:10 UTC, merged