feat: new simultaneous inpainter
HERA-Team/hera_cal pull request #951
Opened 2024-06-12 15:17 UTC by steven-murray

This puts @tyler-a-cox's new simultaneous inpainter into `hera_cal.lst_stack.averaging`.

I refactored it a little so that the algorithm itself, that acts on a single baseline, is its own function. This makes testing it much easier, since you just have to create data arrays that are shape (nnights, nfreqs).

I've put a number of test cases in (as of now, not all of them pass...)

2024-06-13 16:51 UTC, jsdillon requested changes
Just some minor comments, but this generally looks good to me. Thanks @steven-murray

2024-06-14 08:37 UTC, steven-murray commented on hera_cal/lst_stack/averaging.py
> +        A factor to use to down-weight off-diagonal elements of the sample covariance.
Good point. Done.

2024-06-14 08:38 UTC, steven-murray commented on hera_cal/lst_stack/averaging.py
> +    assert np.all(nsamples_by_night == stackn), 'This code assumes that nsamples is constant over frequency for a given night and baseline.'
Yup. Done.

2024-06-14 08:41 UTC, steven-murray commented on hera_cal/lst_stack/averaging.py
> +    filter_half_widths: Sequence[float] = [0.1],
You're right -- I've removed the default.

2024-06-14 08:41 UTC, steven-murray commented on hera_cal/lst_stack/averaging.py
> +    df: un.Quantity['frequency'],
Made it flexible (if a float, assume it's in Hz) and added docs.

2024-06-14 08:41 UTC, steven-murray commented on hera_cal/lst_stack/averaging.py
> +        max_allowed_gap_size = max_gap_factor * filter_half_widths[0]**-1 / df.value
Done.

2024-06-14 08:42 UTC, steven-murray commented on hera_cal/lst_stack/averaging.py
> +        The half-widths of the DPSS filters.
Added that info to the docstring.

2024-06-14 08:50 UTC, steven-murray commented on hera_cal/lst_stack/averaging.py
> +    avg_flgs : np.ndarray | None
You're right. I've updated it.

2024-06-15 13:12 UTC, jsdillon approved these changes

2024-06-18 17:52 UTC, merged