fix: allow to use numpy 2 and pyuvdata 3
HERA-Team/hera_cal pull request #959
Opened 2024-07-05 15:32 UTC by steven-murray

This fixes some warnings and errors from pyuvdata 3 and numpy 2.

2024-07-12 20:11 UTC, jsdillon requested changes
Looks good. Thanks so much @steven-murray for all this! Just a few small questions and I think we'll be good to go.

2024-07-12 20:11 UTC, jsdillon commented on hera_cal/tests/test_io.py
> +                center_loc=uvc.telescope.location
Can't this be done more simply? Do we need to use ENU_from_ECEF?

2024-07-16 16:41 UTC, steven-murray commented on hera_cal/lst_stack/averaging.py
> +    normalizable = ~norm.mask
I think it does, and this would be slightly faster. But to be sure, I've changed it back.

2024-07-16 16:42 UTC, steven-murray commented on hera_cal/tests/test_reflections.py
> +    # ant_dist = {k: np.linalg.norm(v) for k, v in antpos.items()}
Nope. Gone.

2024-07-16 17:11 UTC, jsdillon approved these changes

2024-07-16 17:26 UTC, merged