make sure to copy attributes on subtraction
HERA-Team/hera_cal pull request #961
Opened 2024-07-22 19:20 UTC by dannyjacobs

Subtracting two datacontainers returned a new datacontainer shorn of all attributes. This fixes the problem by always returning the difference with all the attributes of the A, where the difference being computed is A - B.

2024-07-22 19:50 UTC, jsdillon requested changes
Thanks @dannyjacobs!

If you're going to make this change, I'd suggest making parallel changes to `__add__` and `__mult__` and `__floordiv__` and `__truediv__`. I'd also like to see at least one unit test that exposes the issue you were having and is fixed by this change.

2024-07-22 19:50 UTC, jsdillon commented on hera_cal/datacontainer.py
>              newD = copy.deepcopy(self)
This line is now redundant.

2024-07-22 19:50 UTC, jsdillon commented on hera_cal/datacontainer.py
>          otherwise subtract D from each ndarray in self.
I'd edit the docstring to clarify that the original object is always duplicated and that the metadata of the original object is preserved (but not the new object).

2024-07-24 15:43 UTC, dannyjacobs commented
Have made the following changes:
1. Change propagated to add, sub, mul, div
2. Docstring informs about returning a copy object
3. updated test so that it fails without this fix.
4. branch adder_fail adds just the test to the main branch. See main fail!

2024-07-24 16:02 UTC, jsdillon approved these changes
Assuming my change passes tests, I'm good to go. Thanks @dannyjacobs !

2024-07-24 17:06 UTC, merged